version: "3.8"

services:
  goipay_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: goipay_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d goipay_db" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "54321:5432"

  goipay_db_migrations:
    image: ghcr.io/kukymbr/goose-docker:3.21.1
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=goipay_db port=5432 user=postgres password=postgres dbname=goipay_db
    volumes:
      - ./external/goipay/sql/migrations:/migrations
    depends_on:
      goipay_db:
        condition: service_healthy

  goipay:
    image: chekist32/goipay:v0.3.0
    environment:
      - MODE=dev
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - DATABASE_HOST=goipay_db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_NAME=goipay_db
      - XMR_DAEMON_URL=http://node.monerodevs.org:38089
      - XMR_DAEMON_USER=
      - XMR_DAEMON_PASS=
    depends_on:
      goipay_db_migrations:
        condition: service_completed_successfully
    ports:
      - "3000:3000"

  maildev:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - "9080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: update-email
    volumes:
      - ./keycloak/providers:/opt/keycloak/providers
      - ./keycloak/realms:/opt/keycloak/data/import
    command: start-dev --import-realm
    depends_on:
      - maildev

  minio:
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./docker_data/minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped