version: '3.8'

services:
  backend-goipay_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${GOIPAY_DB_NAME:-goipay_db}
      POSTGRES_USER: ${GOIPAY_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${GOIPAY_DB_PASS:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${GOIPAY_DB_USER:-postgres} -d ${GOIPAY_DB_NAME:-goipay_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${GOIPAY_DB_PORT:-5433}:5432"
    networks:
      - goipay_build

  backend-goipay_db_migrations:
    image: chekist32/goose-docker
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=backend-goipay_db port=5432 user=${GOIPAY_DB_USER:-postgres} password=${GOIPAY_DB_PASS:-postgres} dbname=${GOIPAY_DB_NAME:-goipay_db}
    volumes:
      - ./external/goipay/sql/migrations:/migrations
    depends_on:
      backend-goipay_db:
        condition: service_healthy
    networks:
      - goipay_build

  backend-backend_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${SD_DB_NAME:-salmon_donate_backend}
      POSTGRES_USER: ${SD_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${SD_DB_PASS:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SD_DB_USER:-postgres} -d ${SD_DB_NAME:-salmon_donate_backend}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${SD_DB_PORT:-5434}:5432"
    networks:
      - backend_build

  backend-migrations_backend_db:
    image: liquibase/liquibase
    volumes:
      - ./src/main/resources/db:/liquibase/changelog
    command: liquibase --driver=org.postgresql.Driver --url='jdbc:postgresql://backend-backend_db:5432/${SD_DB_NAME:-salmon_donate_backend}' --changeLogFile=./changelog/migrations-master.yml --username=${SD_DB_USER:-postgres} --password=${SD_DB_PASS:-postgres} update
    depends_on:
      backend-backend_db:
        condition: service_healthy
    networks:
      - backend_build

  wait:
    image: busybox:stable
    depends_on:
      backend-goipay_db_migrations:
        condition: service_completed_successfully
      backend-migrations_backend_db:
          condition: service_completed_successfully

networks:
  goipay_build:
  backend_build: