name: CI

on:
  push:
    branches:
      - master
    paths:
      - "keycloak/**"
      - "external/**"
      - "src/**"
      - "pom.xml"
      - ".env.test"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - master
    paths:
      - "keycloak/**"
      - "external/**"
      - "src/**"
      - "pom.xml"
      - ".env.test"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Run Tests
        run: | 
          set -a
          source .env.test
          set +a
          mvn clean test
